export default `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Oracle Reports version 11.1.2.1.0 -->
<DWHD_2013XML>
  <LIST_G_CONTACT_ID>
    <G_CONTACT_ID>
      <FULL_NAME1>Fred Bloggs</FULL_NAME1>
      <CLOSED_DATE>03/AUG/2044</CLOSED_DATE>
      <TP_ORG_NAME></TP_ORG_NAME>
      <PRICE>34.5</PRICE>
      <VAT>6.9</VAT>
      <DUE_TOTAL>41.4</DUE_TOTAL>
      <DUE_SUBTOTAL>41.4</DUE_SUBTOTAL>
      <DUE_VAT>6.9</DUE_VAT>
      <BILLED_FLAG>Y</BILLED_FLAG>
      <DX_ADDRESS>MADE-UP ADDRESS
SEA00</DX_ADDRESS>
      <REQUESTER_ADDRESS>MADE-UP ADDRESS
SEA00
00
MADE-UP CLOSE
MADE-UP TOWN
MADE-UP COUNTY
NE00 0ZZ</REQUESTER_ADDRESS>
      <RECEIVED_DATE3>I attach the replies to your enquiry for the above property dated 02 August 2044.</RECEIVED_DATE3>
      <BILLING_FREQUENCY>W</BILLING_FREQUENCY>
      <OUR_REF>703868/589000</OUR_REF>
      <CONTACT_ID>703868</CONTACT_ID>
      <PRN_NUMBER>589000</PRN_NUMBER>
      <ENQUIRY_DATE>02 AUGUST, 2044</ENQUIRY_DATE>
      <RECEIVED_DATE2>02 AUGUST, 2044</RECEIVED_DATE2>
      <RECEIVED_DATE>02/AUG/2044</RECEIVED_DATE>
      <PAID_TOTAL>41.4</PAID_TOTAL>
      <PAID_SUBTOTAL>34.5</PAID_SUBTOTAL>
      <PAID_VAT>6.9</PAID_VAT>
      <VAT_PERCENTAGE>   20.00 % S</VAT_PERCENTAGE>
      <CHEQUE_NUMBER></CHEQUE_NUMBER>
      <SIGNATURE></SIGNATURE>
      <FULL_NAME></FULL_NAME>
      <JOB_TITLE>Team Supervisor</JOB_TITLE>
      <EXTERNAL_REF>PD/363</EXTERNAL_REF>
      <SYSTEM_DATE>04/SEP/2044</SYSTEM_DATE>
      <DX_NUMBER></DX_NUMBER>
      <FIRST_LINE></FIRST_LINE>
      <SECOND_LINE>100 MADE-UP STREET</SECOND_LINE>
      <THIRD_LINE></THIRD_LINE>
      <FOURTH_LINE>TOW LAW</FOURTH_LINE>
      <FIFTH_LINE>NE00 0XU</FIFTH_LINE>
      <CF_OUR_REF>1</CF_OUR_REF>
      <CF_VAT_PRINT_STATUS>COPY VAT RECEIPT</CF_VAT_PRINT_STATUS>
    </G_CONTACT_ID>
  </LIST_G_CONTACT_ID>
  <LIST_G_QA_SUM_SERVICE_ID>
    <G_QA_SUM_SERVICE_ID>
      <SERVICE_ORDER1>20</SERVICE_ORDER1>
      <SECT_HDR_ORDER1>1</SECT_HDR_ORDER1>
      <SERVICE_ID2>1002483</SERVICE_ID2>
      <SERVICE_NAME>Maps</SERVICE_NAME>
      <LIABILITY_LIMIT></LIABILITY_LIMIT>
      <LIST_G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>1</SECTION_ORDER1>
          <SECTION_ID1>1000680</SECTION_ID1>
          <SECTION_NAME1>Question 1.1</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>1</QUESTION_ORDER1>
              <QUESTION_ID1>84</QUESTION_ID1>
              <QUESTION_NO>1.1</QUESTION_NO>
              <QUESTION_TITLE1>Q N3</QUESTION_TITLE1>
              <QUESTION_TEXT1>Where relevant, please include a copy of an extract from the public sewer map.</QUESTION_TEXT1>
              <ANSWER_ID1>262</ANSWER_ID1>
              <ANSWER_TEXT1>Map Provided</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>2</SECTION_ORDER1>
          <SECTION_ID1>1000681</SECTION_ID1>
          <SECTION_NAME1>Question 1.2</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>2</QUESTION_ORDER1>
              <QUESTION_ID1>68</QUESTION_ID1>
              <QUESTION_NO>1.2</QUESTION_NO>
              <QUESTION_TITLE1>Q N10</QUESTION_TITLE1>
              <QUESTION_TEXT1>Where relevant, please include a copy of an extract from the map of waterworks.</QUESTION_TEXT1>
              <ANSWER_ID1>174</ANSWER_ID1>
              <ANSWER_TEXT1>Map Provided</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
      </LIST_G_QA_SUM_SECTION_ID>
    </G_QA_SUM_SERVICE_ID>
    <G_QA_SUM_SERVICE_ID>
      <SERVICE_ORDER1>20</SERVICE_ORDER1>
      <SECT_HDR_ORDER1>2</SECT_HDR_ORDER1>
      <SERVICE_ID2>1002483</SERVICE_ID2>
      <SERVICE_NAME>Drainage</SERVICE_NAME>
      <LIABILITY_LIMIT></LIABILITY_LIMIT>
      <LIST_G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>3</SECTION_ORDER1>
          <SECTION_ID1>1000753</SECTION_ID1>
          <SECTION_NAME1>Question 2.1</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>3</QUESTION_ORDER1>
              <QUESTION_ID1>85</QUESTION_ID1>
              <QUESTION_NO>2.1</QUESTION_NO>
              <QUESTION_TITLE1>Q N4</QUESTION_TITLE1>
              <QUESTION_TEXT1>Does foul water from the property drain to a public sewer?</QUESTION_TEXT1>
              <ANSWER_ID1>1111</ANSWER_ID1>
              <ANSWER_TEXT1>Yes</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>4</SECTION_ORDER1>
          <SECTION_ID1>1000758</SECTION_ID1>
          <SECTION_NAME1>Question 2.2</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>4</QUESTION_ORDER1>
              <QUESTION_ID1>1000040</QUESTION_ID1>
              <QUESTION_NO>2.2</QUESTION_NO>
              <QUESTION_TITLE1>Q N5a</QUESTION_TITLE1>
              <QUESTION_TEXT1>Does surface water from the property drain to a public sewer?</QUESTION_TEXT1>
              <ANSWER_ID1>271</ANSWER_ID1>
              <ANSWER_TEXT1>Yes</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>5</SECTION_ORDER1>
          <SECTION_ID1>1000768</SECTION_ID1>
          <SECTION_NAME1>Question 2.3</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>5</QUESTION_ORDER1>
              <QUESTION_ID1>1000041</QUESTION_ID1>
              <QUESTION_NO>2.3</QUESTION_NO>
              <QUESTION_TITLE1>Q N17a</QUESTION_TITLE1>
              <QUESTION_TEXT1>Is a surface water drainage charge payable?</QUESTION_TEXT1>
              <ANSWER_ID1>2040</ANSWER_ID1>
              <ANSWER_TEXT1>Yes</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>6</SECTION_ORDER1>
          <SECTION_ID1>1000783</SECTION_ID1>
          <SECTION_NAME1>Question 2.4</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>6</QUESTION_ORDER1>
              <QUESTION_ID1>1000042</QUESTION_ID1>
              <QUESTION_NO>2.4</QUESTION_NO>
              <QUESTION_TITLE1>Q N7a</QUESTION_TITLE1>
              <QUESTION_TEXT1>Does the public sewer map indicate any public sewer, disposal main or lateral drain within the boundaries of the property?</QUESTION_TEXT1>
              <ANSWER_ID1>1000499</ANSWER_ID1>
              <ANSWER_TEXT1>Yes</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>7</SECTION_ORDER1>
          <SECTION_ID1>1000784</SECTION_ID1>
          <SECTION_NAME1>Question 2.4.1</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>7</QUESTION_ORDER1>
              <QUESTION_ID1>1000043</QUESTION_ID1>
              <QUESTION_NO>2.4.1</QUESTION_NO>
              <QUESTION_TITLE1>Q N26</QUESTION_TITLE1>
              <QUESTION_TEXT1>Does the public sewer map indicate any public pumping station or any other ancillary apparatus within the boundaries of the property?</QUESTION_TEXT1>
              <ANSWER_ID1>1000503</ANSWER_ID1>
              <ANSWER_TEXT1>No</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>8</SECTION_ORDER1>
          <SECTION_ID1>1000786</SECTION_ID1>
          <SECTION_NAME1>Question 2.5</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>8</QUESTION_ORDER1>
              <QUESTION_ID1>89</QUESTION_ID1>
              <QUESTION_NO>2.5</QUESTION_NO>
              <QUESTION_TITLE1>Q N8</QUESTION_TITLE1>
              <QUESTION_TEXT1>Does the public sewer map indicate any public sewer within 30.48 metres (100 feet) of any buildings within the property?</QUESTION_TEXT1>
              <ANSWER_ID1>1119</ANSWER_ID1>
              <ANSWER_TEXT1>Yes</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>9</SECTION_ORDER1>
          <SECTION_ID1>1000787</SECTION_ID1>
          <SECTION_NAME1>Question 2.5.1</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>9</QUESTION_ORDER1>
              <QUESTION_ID1>1000044</QUESTION_ID1>
              <QUESTION_NO>2.5.1</QUESTION_NO>
              <QUESTION_TITLE1>Q N27</QUESTION_TITLE1>
              <QUESTION_TEXT1>Does the public sewer map indicate any public pumping station or any other ancillary apparatus within 50 metres  of any buildings within the property?</QUESTION_TEXT1>
              <ANSWER_ID1>1000506</ANSWER_ID1>
              <ANSWER_TEXT1>No</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>10</SECTION_ORDER1>
          <SECTION_ID1>1000788</SECTION_ID1>
          <SECTION_NAME1>Question 2.6</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>10</QUESTION_ORDER1>
              <QUESTION_ID1>1000045</QUESTION_ID1>
              <QUESTION_NO>2.6</QUESTION_NO>
              <QUESTION_TITLE1>Q N6a</QUESTION_TITLE1>
              <QUESTION_TEXT1>Are any sewers or lateral drains serving or which are proposed to serve the property the subject of an existing adoption agreement or an application for such an agreement?</QUESTION_TEXT1>
              <ANSWER_ID1>1000509</ANSWER_ID1>
              <ANSWER_TEXT1>No</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>11</SECTION_ORDER1>
          <SECTION_ID1>1000789</SECTION_ID1>
          <SECTION_NAME1>Question 2.7</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>11</QUESTION_ORDER1>
              <QUESTION_ID1>90</QUESTION_ID1>
              <QUESTION_NO>2.7</QUESTION_NO>
              <QUESTION_TITLE1>Q N9</QUESTION_TITLE1>
              <QUESTION_TEXT1>Has a sewerage undertaker approved or been consulted about any plans to erect a building or extension on the property over or in the vicinity of a public sewer, disposal main or drain?</QUESTION_TEXT1>
              <ANSWER_ID1>1121</ANSWER_ID1>
              <ANSWER_TEXT1>No</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>12</SECTION_ORDER1>
          <SECTION_ID1>1000790</SECTION_ID1>
          <SECTION_NAME1>Question 2.8</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>12</QUESTION_ORDER1>
              <QUESTION_ID1>1000046</QUESTION_ID1>
              <QUESTION_NO>2.8</QUESTION_NO>
              <QUESTION_TITLE1>Q COM10a</QUESTION_TITLE1>
              <QUESTION_TEXT1>Is the building which is or forms part of the property at risk of internal flooding due to overloaded public sewers?</QUESTION_TEXT1>
              <ANSWER_ID1>1000521</ANSWER_ID1>
              <ANSWER_TEXT1>No</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>13</SECTION_ORDER1>
          <SECTION_ID1>1000791</SECTION_ID1>
          <SECTION_NAME1>Question 2.9</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>13</QUESTION_ORDER1>
              <QUESTION_ID1>83</QUESTION_ID1>
              <QUESTION_NO>2.9</QUESTION_NO>
              <QUESTION_TITLE1>Q N25</QUESTION_TITLE1>
              <QUESTION_TEXT1>Please state the distance from the property to the nearest boundary of the nearest sewage treatment works.</QUESTION_TEXT1>
              <ANSWER_ID1>261</ANSWER_ID1>
              <ANSWER_TEXT1>See Answer</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
      </LIST_G_QA_SUM_SECTION_ID>
    </G_QA_SUM_SERVICE_ID>
    <G_QA_SUM_SERVICE_ID>
      <SERVICE_ORDER1>20</SERVICE_ORDER1>
      <SECT_HDR_ORDER1>3</SECT_HDR_ORDER1>
      <SERVICE_ID2>1002483</SERVICE_ID2>
      <SERVICE_NAME>Water</SERVICE_NAME>
      <LIABILITY_LIMIT></LIABILITY_LIMIT>
      <LIST_G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>14</SECTION_ORDER1>
          <SECTION_ID1>1000792</SECTION_ID1>
          <SECTION_NAME1>Question 3.1</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>14</QUESTION_ORDER1>
              <QUESTION_ID1>71</QUESTION_ID1>
              <QUESTION_NO>3.1</QUESTION_NO>
              <QUESTION_TITLE1>Q N13</QUESTION_TITLE1>
              <QUESTION_TEXT1>Is the property connected to mains water supply?</QUESTION_TEXT1>
              <ANSWER_ID1>183</ANSWER_ID1>
              <ANSWER_TEXT1>Yes</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>15</SECTION_ORDER1>
          <SECTION_ID1>1000793</SECTION_ID1>
          <SECTION_NAME1>Question 3.2</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>15</QUESTION_ORDER1>
              <QUESTION_ID1>72</QUESTION_ID1>
              <QUESTION_NO>3.2</QUESTION_NO>
              <QUESTION_TITLE1>Q N14</QUESTION_TITLE1>
              <QUESTION_TEXT1>Are there any water mains, resource mains or discharge pipes within the boundaries of the property?</QUESTION_TEXT1>
              <ANSWER_ID1>190</ANSWER_ID1>
              <ANSWER_TEXT1>No</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>16</SECTION_ORDER1>
          <SECTION_ID1>1000794</SECTION_ID1>
          <SECTION_NAME1>Question 3.3</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>16</QUESTION_ORDER1>
              <QUESTION_ID1>69</QUESTION_ID1>
              <QUESTION_NO>3.3</QUESTION_NO>
              <QUESTION_TITLE1>Q N11</QUESTION_TITLE1>
              <QUESTION_TEXT1>Is any water main or service pipe serving or which is proposed to serve the property the subject of an existing adoption agreement or an application for such an agreement?</QUESTION_TEXT1>
              <ANSWER_ID1>178</ANSWER_ID1>
              <ANSWER_TEXT1>No</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>17</SECTION_ORDER1>
          <SECTION_ID1>1000795</SECTION_ID1>
          <SECTION_NAME1>Question 3.4</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>17</QUESTION_ORDER1>
              <QUESTION_ID1>1000047</QUESTION_ID1>
              <QUESTION_NO>3.4</QUESTION_NO>
              <QUESTION_TITLE1>Q N22a</QUESTION_TITLE1>
              <QUESTION_TEXT1>Is the property at risk of receiving low water pressure or flow?</QUESTION_TEXT1>
              <ANSWER_ID1>1000524</ANSWER_ID1>
              <ANSWER_TEXT1>No</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>18</SECTION_ORDER1>
          <SECTION_ID1>1000796</SECTION_ID1>
          <SECTION_NAME1>Question 3.5</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>18</QUESTION_ORDER1>
              <QUESTION_ID1>1000048</QUESTION_ID1>
              <QUESTION_NO>3.5</QUESTION_NO>
              <QUESTION_TITLE1>Q N23a</QUESTION_TITLE1>
              <QUESTION_TEXT1>What is the classification of the water supply for the property ?</QUESTION_TEXT1>
              <ANSWER_ID1>1000554</ANSWER_ID1>
              <ANSWER_TEXT1>Slightly Hard</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>19</SECTION_ORDER1>
          <SECTION_ID1>1000797</SECTION_ID1>
          <SECTION_NAME1>Question 3.6</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>19</QUESTION_ORDER1>
              <QUESTION_ID1>76</QUESTION_ID1>
              <QUESTION_NO>3.6</QUESTION_NO>
              <QUESTION_TITLE1>Q N18</QUESTION_TITLE1>
              <QUESTION_TEXT1>Please include details of the location of any water meter serving the property.</QUESTION_TEXT1>
              <ANSWER_ID1>212</ANSWER_ID1>
              <ANSWER_TEXT1>No Meter</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
      </LIST_G_QA_SUM_SECTION_ID>
    </G_QA_SUM_SERVICE_ID>
    <G_QA_SUM_SERVICE_ID>
      <SERVICE_ORDER1>20</SERVICE_ORDER1>
      <SECT_HDR_ORDER1>4</SECT_HDR_ORDER1>
      <SERVICE_ID2>1002483</SERVICE_ID2>
      <SERVICE_NAME>Charges</SERVICE_NAME>
      <LIABILITY_LIMIT></LIABILITY_LIMIT>
      <LIST_G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>21</SECTION_ORDER1>
          <SECTION_ID1>1000743</SECTION_ID1>
          <SECTION_NAME1>Question 4.1.1</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>21</QUESTION_ORDER1>
              <QUESTION_ID1>1000049</QUESTION_ID1>
              <QUESTION_NO>4.1.1</QUESTION_NO>
              <QUESTION_TITLE1>Q N12a</QUESTION_TITLE1>
              <QUESTION_TEXT1>Who is responsible for providing the sewerage services for the property ?</QUESTION_TEXT1>
              <ANSWER_ID1>1000602</ANSWER_ID1>
              <ANSWER_TEXT1>NWL</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>22</SECTION_ORDER1>
          <SECTION_ID1>1000744</SECTION_ID1>
          <SECTION_NAME1>Question 4.1.2</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>22</QUESTION_ORDER1>
              <QUESTION_ID1>1000050</QUESTION_ID1>
              <QUESTION_NO>4.1.2</QUESTION_NO>
              <QUESTION_TITLE1>Q N12b</QUESTION_TITLE1>
              <QUESTION_TEXT1>Who is responsible for providing the water services for the property ?</QUESTION_TEXT1>
              <ANSWER_ID1>1000603</ANSWER_ID1>
              <ANSWER_TEXT1>NWL</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>23</SECTION_ORDER1>
          <SECTION_ID1>1000746</SECTION_ID1>
          <SECTION_NAME1>Question 4.2</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>23</QUESTION_ORDER1>
              <QUESTION_ID1>77</QUESTION_ID1>
              <QUESTION_NO>4.2</QUESTION_NO>
              <QUESTION_TITLE1>Q N19</QUESTION_TITLE1>
              <QUESTION_TEXT1>Who bills the property for sewerage services?</QUESTION_TEXT1>
              <ANSWER_ID1>218</ANSWER_ID1>
              <ANSWER_TEXT1>Northumbrian Water</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>24</SECTION_ORDER1>
          <SECTION_ID1>1000747</SECTION_ID1>
          <SECTION_NAME1>Question 4.3</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>24</QUESTION_ORDER1>
              <QUESTION_ID1>78</QUESTION_ID1>
              <QUESTION_NO>4.3</QUESTION_NO>
              <QUESTION_TITLE1>Q N20</QUESTION_TITLE1>
              <QUESTION_TEXT1>Who bills the property for water services?</QUESTION_TEXT1>
              <ANSWER_ID1>223</ANSWER_ID1>
              <ANSWER_TEXT1>Northumbrian Water</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>25</SECTION_ORDER1>
          <SECTION_ID1>1000751</SECTION_ID1>
          <SECTION_NAME1>Question 4.4</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>25</QUESTION_ORDER1>
              <QUESTION_ID1>73</QUESTION_ID1>
              <QUESTION_NO>4.4</QUESTION_NO>
              <QUESTION_TITLE1>Q N15</QUESTION_TITLE1>
              <QUESTION_TEXT1>What is the current basis for charging for sewerage and water services at the property?</QUESTION_TEXT1>
              <ANSWER_ID1>197</ANSWER_ID1>
              <ANSWER_TEXT1>Unmeasured</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
        <G_QA_SUM_SECTION_ID>
          <SECTION_ORDER1>26</SECTION_ORDER1>
          <SECTION_ID1>1000752</SECTION_ID1>
          <SECTION_NAME1>Question 4.5</SECTION_NAME1>
          <LIST_G_QA_SUM_QA>
            <G_QA_SUM_QA>
              <QUESTION_ORDER1>26</QUESTION_ORDER1>
              <QUESTION_ID1>74</QUESTION_ID1>
              <QUESTION_NO>4.5</QUESTION_NO>
              <QUESTION_TITLE1>Q N16</QUESTION_TITLE1>
              <QUESTION_TEXT1>Will the basis for charging for sewerage and water services at the property change as a consequence of a change of occupation?</QUESTION_TEXT1>
              <ANSWER_ID1>204</ANSWER_ID1>
              <ANSWER_TEXT1>No Change</ANSWER_TEXT1>
            </G_QA_SUM_QA>
          </LIST_G_QA_SUM_QA>
        </G_QA_SUM_SECTION_ID>
      </LIST_G_QA_SUM_SECTION_ID>
    </G_QA_SUM_SERVICE_ID>
  </LIST_G_QA_SUM_SERVICE_ID>
  <LIST_G_QA_DET_SERVICE_ID>
    <G_QA_DET_SERVICE_ID>
      <SERVICE_ORDER>20</SERVICE_ORDER>
      <SECT_HDR_ORDER>1</SECT_HDR_ORDER>
      <SERVICE_ID>1002483</SERVICE_ID>
      <SERVICE_NAME1>Maps</SERVICE_NAME1>
      <LIST_G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>1</SECTION_ORDER>
          <SECTION_ID>1000680</SECTION_ID>
          <SECTION_NAME>Question 1.1</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>1</QUESTION_ORDER>
              <QUESTION_ID>84</QUESTION_ID>
              <QUESTION_TITLE>Q N3</QUESTION_TITLE>
              <QUESTION_TEXT>Where relevant, please include a copy of an extract from the public sewer map.</QUESTION_TEXT>
              <ANSWER_ID>262</ANSWER_ID>
              <ANSWER_TEXT>A copy of an extract of the public sewer map is included, showing the public sewers, disposal mains and lateral drains in the vicinity of the property.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. The Water Industry Act 1991 defines Public Sewers as those which Northumbrian Water has responsibility for. Other assets and rivers, watercourses, ponds, culverts or highway drains may be shown for information purposes only. 

2. Any private sewers or lateral drains which are indicated on the extract of the public sewer map as being subject to an agreement under Section 104 of the Water Industry Act 1991 are not an as constructed ' record. It is recommended these details be checked with the developer.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>2</SECTION_ORDER>
          <SECTION_ID>1000681</SECTION_ID>
          <SECTION_NAME>Question 1.2</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>2</QUESTION_ORDER>
              <QUESTION_ID>68</QUESTION_ID>
              <QUESTION_TITLE>Q N10</QUESTION_TITLE>
              <QUESTION_TEXT>Where relevant, please include a copy of an extract from the map of waterworks.</QUESTION_TEXT>
              <ANSWER_ID>174</ANSWER_ID>
              <ANSWER_TEXT>A copy of an extract of the map of waterworks is included, showing water mains, resource mains or discharge pipes in the vicinity of the property.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. The &quot;water mains&quot; in this context are those which are vested in and maintainable by the water company under statute.
2. Assets other than public water mains may be shown on the plan, for information only.
3. Water companies are not responsible for private supply pipes connecting the property to the public water main and do not hold details of these. These may pass through land outside of the control of the seller, or may be shared with adjacent properties. The buyer may wish to investigate whether separate rights or easements are needed for their inspection, repair or renewal.
4. The enclosed extract of the public water main record shows known public water mains in the vicinity of the property. It should be possible to estimate the likely length and route of any private water supply pipe connecting the property to the public water network.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
      </LIST_G_QA_DET_SECTION_ID>
      <CP_LAST_SERVICE_2></CP_LAST_SERVICE_2>
      <CP_LAST_SERVICE_1>1002483</CP_LAST_SERVICE_1>
      <CF_LAST_SERVICE>1</CF_LAST_SERVICE>
    </G_QA_DET_SERVICE_ID>
    <G_QA_DET_SERVICE_ID>
      <SERVICE_ORDER>20</SERVICE_ORDER>
      <SECT_HDR_ORDER>2</SECT_HDR_ORDER>
      <SERVICE_ID>1002483</SERVICE_ID>
      <SERVICE_NAME1>Drainage</SERVICE_NAME1>
      <LIST_G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>3</SECTION_ORDER>
          <SECTION_ID>1000753</SECTION_ID>
          <SECTION_NAME>Question 2.1</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>3</QUESTION_ORDER>
              <QUESTION_ID>85</QUESTION_ID>
              <QUESTION_TITLE>Q N4</QUESTION_TITLE>
              <QUESTION_TEXT>Does foul water from the property drain to a public sewer?</QUESTION_TEXT>
              <ANSWER_ID>1111</ANSWER_ID>
              <ANSWER_TEXT>Records indicate that foul water from the property drains to a public sewer.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. Water companies are not responsible for any private drains and sewers that connect the property to the public sewerage system, and do not hold details of these. The property owner will normally have sole responsibility for private drains serving the property and may have shared responsibility, with other users, if the property is served by a private sewer which also serves other properties. These may pass through land outside of the control of the seller and the buyer may wish to investigate whether separate rights or easements are needed for their inspection, repair or renewal.

2. An extract from the public sewer map is enclosed. This will show known public sewers in the vicinity of the property and it should be possible to estimate the likely length and route of any private drains and/or sewers connecting the property to the public sewerage system.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>4</SECTION_ORDER>
          <SECTION_ID>1000758</SECTION_ID>
          <SECTION_NAME>Question 2.2</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>4</QUESTION_ORDER>
              <QUESTION_ID>1000040</QUESTION_ID>
              <QUESTION_TITLE>Q N5a</QUESTION_TITLE>
              <QUESTION_TEXT>Does surface water from the property drain to a public sewer?</QUESTION_TEXT>
              <ANSWER_ID>271</ANSWER_ID>
              <ANSWER_TEXT>Records indicate that surface water from the property does drain to a public sewer.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. Water companies are not responsible for private drains and sewers that connect the property to the public sewerage system and do not hold details of these.
2. The property owner will normally have sole responsibility for private drains serving the property and may have shared responsibility with other users, if the property is served by a private sewer which also serves other properties. These may pass through land outside of the control of the seller and the buyer may wish to investigate whether separate rights or easements are needed for their inspection, repair or renewal.
3. In some cases, water company records do not distinguish between foul and surface water connections to the public sewerage system.
4. If on inspection the buyer finds that the property is not connected for surface water drainage, the property may be eligible for a rebate of the surface water drainage charge. Details can be obtained from the company.
5. An extract from the public sewer map is enclosed. This will show known public sewers in the vicinity of the property and it should be possible to estimate the likely length and route of any private drains and/or sewers connecting the property to the public sewerage system.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>5</SECTION_ORDER>
          <SECTION_ID>1000768</SECTION_ID>
          <SECTION_NAME>Question 2.3</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>5</QUESTION_ORDER>
              <QUESTION_ID>1000041</QUESTION_ID>
              <QUESTION_TITLE>Q N17a</QUESTION_TITLE>
              <QUESTION_TEXT>Is a surface water drainage charge payable?</QUESTION_TEXT>
              <ANSWER_ID>2040</ANSWER_ID>
              <ANSWER_TEXT>Records confirm that a surface water drainage charge is payable for the property, for the year commencing 1st April 2044, at £67.30 if charged on an unmeasured tariff or £59.84 if charged on a metered tariff.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. Water and sewerage companies full charges are set out in their charges schemes which are available from the company free of charge upon request. The current Northumbrian Water scheme is the 2015/16 Charges Scheme (Household). 
https://www.nwl.co.uk/your-home/your-account/tariffs-and-charges.aspx

2. The Water Industry Act 1991 Section 150, The Water Resale Order 2001 provides protection for people who buy their water or sewerage services from a person or company instead of directly from a water or sewerage company. Details are available from the Office of Water Services (OFWAT).</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>6</SECTION_ORDER>
          <SECTION_ID>1000783</SECTION_ID>
          <SECTION_NAME>Question 2.4</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>6</QUESTION_ORDER>
              <QUESTION_ID>1000042</QUESTION_ID>
              <QUESTION_TITLE>Q N7a</QUESTION_TITLE>
              <QUESTION_TEXT>Does the public sewer map indicate any public sewer, disposal main or lateral drain within the boundaries of the property?</QUESTION_TEXT>
              <ANSWER_ID>1000499</ANSWER_ID>
              <ANSWER_TEXT>The public sewer map indicates that there are sewers or lateral drains within the boundaries of the property.  However, from the1st October 2011 there may be additional public sewers, disposal mains or lateral drains which are not recorded on the public sewer map but which may further prevent or restrict development of the property. For further information contact Northumbrian Water Property Solutions on 0370 2417408.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. The boundary of the property has been determined by reference to the Ordnance Survey record.

2. The presence of a public sewer running within the boundary of the property may restrict further development. The company has a statutory right of access to carry out work on its assets, subject to notice. This may result in employees of the company or its contractors needing to enter the property to carry out work.

3. A Garden over Agreement may affect a property where the land has changed from public open space to a private garden. If the property is affected this will be shown on the Public Sewer map highlighted with an orange box with the letters GO. A Garden over Agreement restricts the occupier from planting trees, building with foundations or substantially altering soil depths over or near to the public sewer. If your property is affected and you would like further details please contact us on 0870 241 7408.

4. Please note if the property was constructed after 1st July 2011 any sewers and/or lateral drains within the boundary of the property are the responsibility of the householder.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>7</SECTION_ORDER>
          <SECTION_ID>1000784</SECTION_ID>
          <SECTION_NAME>Question 2.4.1</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>7</QUESTION_ORDER>
              <QUESTION_ID>1000043</QUESTION_ID>
              <QUESTION_TITLE>Q N26</QUESTION_TITLE>
              <QUESTION_TEXT>Does the public sewer map indicate any public pumping station or any other ancillary apparatus within the boundaries of the property?</QUESTION_TEXT>
              <ANSWER_ID>1000503</ANSWER_ID>
              <ANSWER_TEXT>The public sewer map included indicates that there is no public pumping station within the boundaries of the property. Any other ancillary apparatus is shown on the public sewer map and referenced on the legend.</ANSWER_TEXT>
              <INFORMATIVE_TEXT></INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>8</SECTION_ORDER>
          <SECTION_ID>1000786</SECTION_ID>
          <SECTION_NAME>Question 2.5</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>8</QUESTION_ORDER>
              <QUESTION_ID>89</QUESTION_ID>
              <QUESTION_TITLE>Q N8</QUESTION_TITLE>
              <QUESTION_TEXT>Does the public sewer map indicate any public sewer within 30.48 metres (100 feet) of any buildings within the property?</QUESTION_TEXT>
              <ANSWER_ID>1119</ANSWER_ID>
              <ANSWER_TEXT>The public sewer map included indicates that there is a public sewer within 30.48 metres (100 feet) of a building within the property.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. From the 1st October 2011 there may be additional lateral drains and/or public sewers which are not recorded on the public sewer map but are also within 30.48 metres (100 feet) of a building within the property.

2. The presence of a public sewer within 30.48 metres (100 feet) of the building(s) within the property can result in the local authority requiring a property to be connected to the public sewer.

3. The measure is estimated from the Ordnance Survey record, between the  building(s) within the boundary of the property and the nearest public sewer.

4. Sewers indicated on the extract of the public sewer map as being subject to an agreement under section 104 of the Water Industry Act 1991 are not an as constructed¿ record. It is recommended that these details are checked with the developer.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>9</SECTION_ORDER>
          <SECTION_ID>1000787</SECTION_ID>
          <SECTION_NAME>Question 2.5.1</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>9</QUESTION_ORDER>
              <QUESTION_ID>1000044</QUESTION_ID>
              <QUESTION_TITLE>Q N27</QUESTION_TITLE>
              <QUESTION_TEXT>Does the public sewer map indicate any public pumping station or any other ancillary apparatus within 50 metres  of any buildings within the property?</QUESTION_TEXT>
              <ANSWER_ID>1000506</ANSWER_ID>
              <ANSWER_TEXT>The public sewer map included indicates that there is no public pumping station within 50 metres of any buildings within the property. Any other ancillary apparatus is shown on the public sewer map and referenced on the legend.</ANSWER_TEXT>
              <INFORMATIVE_TEXT></INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>10</SECTION_ORDER>
          <SECTION_ID>1000788</SECTION_ID>
          <SECTION_NAME>Question 2.6</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>10</QUESTION_ORDER>
              <QUESTION_ID>1000045</QUESTION_ID>
              <QUESTION_TITLE>Q N6a</QUESTION_TITLE>
              <QUESTION_TEXT>Are any sewers or lateral drains serving or which are proposed to serve the property the subject of an existing adoption agreement or an application for such an agreement?</QUESTION_TEXT>
              <ANSWER_ID>1000509</ANSWER_ID>
              <ANSWER_TEXT>The property is part of an established or new development and is not subject to an adoption agreement.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. This enquiry is of interest to purchasers of new homes who will want to know whether or not the property will be linked to a public sewer 

2. Where the property is part of a very recent or ongoing development and the sewers are not the subject of an adoption application, buyers should consult with the developer to ascertain the extent of private drains and sewers for which they will hold maintenance and renewal liabilities.

3. Any sewers and/or lateral drains within the boundary of the property are not the the subject of an adoption agreement and remain the responsibility of the householder. Adoptable sewers are normally those situated in the public highway.

4. Please note this could relate to a piece of land that is not part of an established development and is not subject to an adoption agreement.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>11</SECTION_ORDER>
          <SECTION_ID>1000789</SECTION_ID>
          <SECTION_NAME>Question 2.7</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>11</QUESTION_ORDER>
              <QUESTION_ID>90</QUESTION_ID>
              <QUESTION_TITLE>Q N9</QUESTION_TITLE>
              <QUESTION_TEXT>Has a sewerage undertaker approved or been consulted about any plans to erect a building or extension on the property over or in the vicinity of a public sewer, disposal main or drain?</QUESTION_TEXT>
              <ANSWER_ID>1121</ANSWER_ID>
              <ANSWER_TEXT>There are no records in relation to any approval or consultation about plans to erect a building or extension on the property over or in the vicinity of a public sewer, disposal main or drain. However, the sewerage undertaker might not be aware of a building or extension on the property over or in the vicinity of a public sewer, disposal main or drain.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. Buildings or extensions erected over a sewer in contravention of building controls may have to be removed or altered

2. From the 1st October 2011 private sewers, disposal mains and lateral drains were transferred into public ownership and the sewerage undertaker may not have been approved or consulted about any plans to erect a building or extension on the property over or in the vicinity of these.
</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>12</SECTION_ORDER>
          <SECTION_ID>1000790</SECTION_ID>
          <SECTION_NAME>Question 2.8</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>12</QUESTION_ORDER>
              <QUESTION_ID>1000046</QUESTION_ID>
              <QUESTION_TITLE>Q COM10a</QUESTION_TITLE>
              <QUESTION_TEXT>Is the building which is or forms part of the property at risk of internal flooding due to overloaded public sewers?</QUESTION_TEXT>
              <ANSWER_ID>1000521</ANSWER_ID>
              <ANSWER_TEXT>The property is not recorded as being at risk of internal flooding due to overloaded public sewers.  From the 1st October 2011 private sewers, disposal mains and lateral drains were transferred into public ownership. It is therefore possible that a property may be at risk of internal flooding due to an overloaded public sewer which the sewerage undertaker is not aware of. For further information it is recommended that enquiries are made of the vendor.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>A sewer is &quot;overloaded&quot; when the flow from a storm is unable to pass through it due to a permanent problem (e.g. flat gradient, small diameter). Flooding as a result of temporary problems such as blockages, siltation, collapses and equipment or operational failures are excluded. 

&quot;Internal flooding&quot; from public sewers is defined as flooding which enters a building or passes below a suspended floor. For reporting purposes, buildings are restricted to those normally occupied and used for residential, public, commercial, business or industrial purposes. Flooding to garages and outbuildings is not reported.

&quot;At Risk&quot; properties are those that the water company has defined as properties that have suffered or are likely to suffer internal flooding from public foul, combined or surface water sewers due to overloading of the sewerage system.

Flooding as a result of storm events proven to be exceptional and beyond a reference period of one in ten years are not included.

Properties may be at risk of flooding but not included where flooding incidents have not been reported to the Company.

Public Sewers are defined as those for which the Company holds statutory responsibility under the Water Industry Act 1991.

It should be noted that flooding can occur from sewers and drains which are not the responsibility of the Company.  This report excludes such flooding and the Company makes no comment upon this matter.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>13</SECTION_ORDER>
          <SECTION_ID>1000791</SECTION_ID>
          <SECTION_NAME>Question 2.9</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>13</QUESTION_ORDER>
              <QUESTION_ID>83</QUESTION_ID>
              <QUESTION_TITLE>Q N25</QUESTION_TITLE>
              <QUESTION_TEXT>Please state the distance from the property to the nearest boundary of the nearest sewage treatment works.</QUESTION_TEXT>
              <ANSWER_ID>261</ANSWER_ID>
              <ANSWER_TEXT>The nearest sewage treatment works is 258 kilometres South Easterly of the property.  The name of the sewage treatment works is Sunderland Secondary S.T.W..</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. The nearest sewage treatment works will not always be the sewage treatment works serving the catchment within which the property is situated.

2. The Sewerage undertakers records were inspected to determine the nearest sewage treatment works. It should be noted therefore that there may be a private 
sewage treatment works closer than the one detailed above that have not been identified.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
      </LIST_G_QA_DET_SECTION_ID>
      <CP_LAST_SERVICE_2>1002483</CP_LAST_SERVICE_2>
      <CP_LAST_SERVICE_1>1002483</CP_LAST_SERVICE_1>
      <CF_LAST_SERVICE>1</CF_LAST_SERVICE>
    </G_QA_DET_SERVICE_ID>
    <G_QA_DET_SERVICE_ID>
      <SERVICE_ORDER>20</SERVICE_ORDER>
      <SECT_HDR_ORDER>3</SECT_HDR_ORDER>
      <SERVICE_ID>1002483</SERVICE_ID>
      <SERVICE_NAME1>Water</SERVICE_NAME1>
      <LIST_G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>14</SECTION_ORDER>
          <SECTION_ID>1000792</SECTION_ID>
          <SECTION_NAME>Question 3.1</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>14</QUESTION_ORDER>
              <QUESTION_ID>71</QUESTION_ID>
              <QUESTION_TITLE>Q N13</QUESTION_TITLE>
              <QUESTION_TEXT>Is the property connected to mains water supply?</QUESTION_TEXT>
              <ANSWER_ID>183</ANSWER_ID>
              <ANSWER_TEXT>Records indicate that the property is connected to mains water supply.</ANSWER_TEXT>
              <INFORMATIVE_TEXT></INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>15</SECTION_ORDER>
          <SECTION_ID>1000793</SECTION_ID>
          <SECTION_NAME>Question 3.2</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>15</QUESTION_ORDER>
              <QUESTION_ID>72</QUESTION_ID>
              <QUESTION_TITLE>Q N14</QUESTION_TITLE>
              <QUESTION_TEXT>Are there any water mains, resource mains or discharge pipes within the boundaries of the property?</QUESTION_TEXT>
              <ANSWER_ID>190</ANSWER_ID>
              <ANSWER_TEXT>The map of waterworks does not indicate any water mains, resource mains or discharge pipes within the boundaries of the property.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. The boundary of the property has been determined by reference to the Ordnance Survey record.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>16</SECTION_ORDER>
          <SECTION_ID>1000794</SECTION_ID>
          <SECTION_NAME>Question 3.3</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>16</QUESTION_ORDER>
              <QUESTION_ID>69</QUESTION_ID>
              <QUESTION_TITLE>Q N11</QUESTION_TITLE>
              <QUESTION_TEXT>Is any water main or service pipe serving or which is proposed to serve the property the subject of an existing adoption agreement or an application for such an agreement?</QUESTION_TEXT>
              <ANSWER_ID>178</ANSWER_ID>
              <ANSWER_TEXT>Records confirm that water mains or service pipes serving the property are not the subject of an existing adoption agreement or an application for such an agreement.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. This enquiry is of interest to purchasers of new homes who will want to know whether or not the property will be linked to the mains water supply.

2. Please note this could relate to a piece of land and is not subject to an adoption agreement.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>17</SECTION_ORDER>
          <SECTION_ID>1000795</SECTION_ID>
          <SECTION_NAME>Question 3.4</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>17</QUESTION_ORDER>
              <QUESTION_ID>1000047</QUESTION_ID>
              <QUESTION_TITLE>Q N22a</QUESTION_TITLE>
              <QUESTION_TEXT>Is the property at risk of receiving low water pressure or flow?</QUESTION_TEXT>
              <ANSWER_ID>1000524</ANSWER_ID>
              <ANSWER_TEXT>Records confirm that the property is not recorded by the water undertaker as being at risk of receiving low water pressure or flow.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. &quot;Low water pressure&quot; means water pressure below the regulatory reference level which is the minimum pressure when demand on the system is not abnormal.

2. Water Companies are required to include in the Regulatory Register that is reported annually to Ofwat properties receiving pressure below the reference level, provided that allowable exclusions do not apply (i.e. events which can cause pressure to temporarily fall below the reference level).

3. The reference level of service is a flow of 9 litres/minute at a pressure of 10 metres head on the customer's side of the main stop tap (mst). The reference level of service must be applied on the customer's side of a meter or any other company fittings that are on the customer's side of the main stop tap.
The reference level applies to a single property. Where more than one property is served by a common service pipe, the flow assumed in the reference level must be appropriately increased to take account of the total number of properties served.
For two properties, a flow of 18 litres/minute at a pressure of 10metres head on the customers' side of the mst is appropriate. For three or more properties the appropriate flow should be calculated from the standard loadings provided in BS806-3   or Institute of Plumbing handbook.

Because of the difficulty in measuring  pressure and flow at the main stop tap, companies may measure against a surrogate reference level. Companies should use a surrogate of 15 metres head in the adjacent distribution main unless a different level can be shown to be suitable. In some circumstances companies may need to use a surrogate pressure greater than 15 metres to ensure that the reference level is supplied at the customer's side of the main stop tap (for example in areas with small diameter or shared communication pipes).

4. Allowable exclusions 
The Company is required to include in the Regulatory Register properties receiving pressure below the reference level, provided that allowable exclusions listed below do not apply: 
     Abnormal demand: 
This exclusion is intended to cover abnormal peaks in demand and not the daily, weekly or monthly peaks in demand which are normally expected. Companies should exclude from the reported low pressure figures properties which are affected by low pressure only on those days with the highest peak demands. During the report year companies may exclude, for each property, up to five days of low pressure caused by peak demand.
Planned maintenance:  
Companies should not report under low pressures caused by planned maintenance. It is not intended that companies identify the number of properties affected in each instance. However, companies must maintain sufficiently accurate records to verify that low pressure incidents that are excluded from low pressure because of planned maintenance are actually caused by maintenance.
One-off incidents: 
This exclusion covers a number of causes of low pressure; mains bursts;    Failures of company equipment (such as PRVs or booster pumps); Fire fighting; and Action by a third party. However, if problems of this type affect a property frequently, they cannot be classed as one-off events and further investigation will be required before they can be excluded.
Low pressure incidents of short duration: 
Properties affected by low pressures which only occur for a short period, and for which there is evidence that incidents of a longer duration would not occur during the course of the year, may be excluded from the reported low pressure  figures.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>18</SECTION_ORDER>
          <SECTION_ID>1000796</SECTION_ID>
          <SECTION_NAME>Question 3.5</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>18</QUESTION_ORDER>
              <QUESTION_ID>1000048</QUESTION_ID>
              <QUESTION_TITLE>Q N23a</QUESTION_TITLE>
              <QUESTION_TEXT>What is the classification of the water supply for the property ?</QUESTION_TEXT>
              <ANSWER_ID>1000554</ANSWER_ID>
              <ANSWER_TEXT>The water supplied to the property has an average water hardness of 48.75 mg/l Calcium which is defined as Slightly Hard by Northumbrian Water Limited.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>Water hardness can be expressed in various indices, for example, the hardness settings for dishwashers are commonly expressed in Clark's degrees, but check with the manufacturer as there are also other units. The following table shows the normal range of hardness.

Value                           mg/l of Calcium                English Clark        French          General/German
                                                                             Degrees               Degrees        Degrees
Soft                               0.00  to 20.00                    0 to 3.5		            0 to 5                0 to 2.8
Moderately Soft	          20.01 to 40.00                 3.6 to 7		               6 to 10           2.9 to 5.6
Slightly Hard                40.01 to 60.00                    8 to 10.5	         11 to 15           5.7 to 8.4
Moderately Hard          60.01 to 80.00               10.6 to 14		           16 to 20           8.5 to 11.2
Hard	                            80.01 to 120.00                15 to 21	            21 to 30         11.3 to 16.8
Very Hard	                    Over 120.00                     Over 21		           Over 30           Over 16.8</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>19</SECTION_ORDER>
          <SECTION_ID>1000797</SECTION_ID>
          <SECTION_NAME>Question 3.6</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>19</QUESTION_ORDER>
              <QUESTION_ID>76</QUESTION_ID>
              <QUESTION_TITLE>Q N18</QUESTION_TITLE>
              <QUESTION_TEXT>Please include details of the location of any water meter serving the property.</QUESTION_TEXT>
              <ANSWER_ID>212</ANSWER_ID>
              <ANSWER_TEXT>Records indicate that the property is not served by a water meter.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. Where the property is not served by a meter and the customer wishes to consider this method of charging they should contact:
Northumbrian Water Limited, PO Box 300 Durham DH1 9ZR
0845 733 5566
www.nwl.co.uk</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
      </LIST_G_QA_DET_SECTION_ID>
      <CP_LAST_SERVICE_2>1002483</CP_LAST_SERVICE_2>
      <CP_LAST_SERVICE_1>1002483</CP_LAST_SERVICE_1>
      <CF_LAST_SERVICE>1</CF_LAST_SERVICE>
    </G_QA_DET_SERVICE_ID>
    <G_QA_DET_SERVICE_ID>
      <SERVICE_ORDER>20</SERVICE_ORDER>
      <SECT_HDR_ORDER>4</SECT_HDR_ORDER>
      <SERVICE_ID>1002483</SERVICE_ID>
      <SERVICE_NAME1>Charges</SERVICE_NAME1>
      <LIST_G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>21</SECTION_ORDER>
          <SECTION_ID>1000743</SECTION_ID>
          <SECTION_NAME>Question 4.1.1</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>21</QUESTION_ORDER>
              <QUESTION_ID>1000049</QUESTION_ID>
              <QUESTION_TITLE>Q N12a</QUESTION_TITLE>
              <QUESTION_TEXT>Who is responsible for providing the sewerage services for the property ?</QUESTION_TEXT>
              <ANSWER_ID>1000602</ANSWER_ID>
              <ANSWER_TEXT>Northumbrian Water Limited is responsible for providing the sewerage services for the property.</ANSWER_TEXT>
              <INFORMATIVE_TEXT></INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>22</SECTION_ORDER>
          <SECTION_ID>1000744</SECTION_ID>
          <SECTION_NAME>Question 4.1.2</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>22</QUESTION_ORDER>
              <QUESTION_ID>1000050</QUESTION_ID>
              <QUESTION_TITLE>Q N12b</QUESTION_TITLE>
              <QUESTION_TEXT>Who is responsible for providing the water services for the property ?</QUESTION_TEXT>
              <ANSWER_ID>1000603</ANSWER_ID>
              <ANSWER_TEXT>Northumbrian Water Limited is responsible for providing the water services for the property.</ANSWER_TEXT>
              <INFORMATIVE_TEXT></INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>23</SECTION_ORDER>
          <SECTION_ID>1000746</SECTION_ID>
          <SECTION_NAME>Question 4.2</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>23</QUESTION_ORDER>
              <QUESTION_ID>77</QUESTION_ID>
              <QUESTION_TITLE>Q N19</QUESTION_TITLE>
              <QUESTION_TEXT>Who bills the property for sewerage services?</QUESTION_TEXT>
              <ANSWER_ID>218</ANSWER_ID>
              <ANSWER_TEXT>The property is billed for sewerage services by:
Northumbrian Water Limited, PO Box 300 Durham DH1 9ZR
0345 733 5566
www.nwl.co.uk</ANSWER_TEXT>
              <INFORMATIVE_TEXT></INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>24</SECTION_ORDER>
          <SECTION_ID>1000747</SECTION_ID>
          <SECTION_NAME>Question 4.3</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>24</QUESTION_ORDER>
              <QUESTION_ID>78</QUESTION_ID>
              <QUESTION_TITLE>Q N20</QUESTION_TITLE>
              <QUESTION_TEXT>Who bills the property for water services?</QUESTION_TEXT>
              <ANSWER_ID>223</ANSWER_ID>
              <ANSWER_TEXT>The property is billed for water services by:
Northumbrian Water Limited, PO Box 300 Durham DH1 9ZR
0345 733 5566
www.nwl.co.uk</ANSWER_TEXT>
              <INFORMATIVE_TEXT></INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>25</SECTION_ORDER>
          <SECTION_ID>1000751</SECTION_ID>
          <SECTION_NAME>Question 4.4</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>25</QUESTION_ORDER>
              <QUESTION_ID>73</QUESTION_ID>
              <QUESTION_TITLE>Q N15</QUESTION_TITLE>
              <QUESTION_TEXT>What is the current basis for charging for sewerage and water services at the property?</QUESTION_TEXT>
              <ANSWER_ID>197</ANSWER_ID>
              <ANSWER_TEXT>The charges are based on the rateable value of the property of £10 and the charge for the current financial year is £300.64;</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. Water and sewerage companies full charges are set out in their charges schemes which are available from the company free of charge upon request.

2. The Company may install a meter at the premises where a buyer makes a change of use of the property or where the buyer uses water for: Watering the garden, other by hand (this includes the use of sprinklers)
Automatically replenishing a pond or swimming pool with a capacity greater than 10,000 litres.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
        <G_QA_DET_SECTION_ID>
          <SECTION_ORDER>26</SECTION_ORDER>
          <SECTION_ID>1000752</SECTION_ID>
          <SECTION_NAME>Question 4.5</SECTION_NAME>
          <LIST_G_QA_DET_QA>
            <G_QA_DET_QA>
              <QUESTION_ORDER>26</QUESTION_ORDER>
              <QUESTION_ID>74</QUESTION_ID>
              <QUESTION_TITLE>Q N16</QUESTION_TITLE>
              <QUESTION_TEXT>Will the basis for charging for sewerage and water services at the property change as a consequence of a change of occupation?</QUESTION_TEXT>
              <ANSWER_ID>204</ANSWER_ID>
              <ANSWER_TEXT>There will be no change in the current charging arrangements as a consequence of a change of occupation.</ANSWER_TEXT>
              <INFORMATIVE_TEXT>1. Water and sewerage companies full charges are set out in their charges schemes which are available from the company free of charge upon request.

2. The Company may install a meter at the premises where a buyer makes a change of use of the property or where the buyer uses water for: Watering the garden, other by hand (this includes the use of sprinklers)
Automatically replenishing a pond or swimming pool with a capacity greater than 10,000 litres.

3. Where charges are levied to a third party, the occupier needs to contact the vendor to confirm charging arrangements.</INFORMATIVE_TEXT>
            </G_QA_DET_QA>
          </LIST_G_QA_DET_QA>
        </G_QA_DET_SECTION_ID>
      </LIST_G_QA_DET_SECTION_ID>
      <CP_LAST_SERVICE_2>1002483</CP_LAST_SERVICE_2>
      <CP_LAST_SERVICE_1>1002483</CP_LAST_SERVICE_1>
      <CF_LAST_SERVICE>1</CF_LAST_SERVICE>
    </G_QA_DET_SERVICE_ID>
  </LIST_G_QA_DET_SERVICE_ID>
  <LIST_G_SERVICE_PRICE>
    <G_SERVICE_PRICE>
      <TAX_CODE></TAX_CODE>
      <CONTACT_ID1>703868</CONTACT_ID1>
      <SERVICE_ID1>1002483</SERVICE_ID1>
      <PB_SERVICE_NAME>Northumbrian Water CON29DW</PB_SERVICE_NAME>
      <CONTACT_ID2>703868</CONTACT_ID2>
      <PB_PRICE>34.5</PB_PRICE>
      <PB_VAT>6.9</PB_VAT>
      <PB_VAT_PCT>20</PB_VAT_PCT>
      <PB_TOTAL_COST>41.4</PB_TOTAL_COST>
      <MENU_ORDER>20</MENU_ORDER>
      <PB_STATUS>C</PB_STATUS>
      <PB_PRINTED_DATE>03-AUG-16</PB_PRINTED_DATE>
      <CF_PRINT_STATUS>Reprint</CF_PRINT_STATUS>
    </G_SERVICE_PRICE>
  </LIST_G_SERVICE_PRICE>
  <LIST_G_GIF_NAME>
    <G_GIF_NAME>
      <GIF_NAME>703800_W.gif</GIF_NAME>
    </G_GIF_NAME>
    <G_GIF_NAME>
      <GIF_NAME>703800_S.gif</GIF_NAME>
    </G_GIF_NAME>
  </LIST_G_GIF_NAME>
  <CP_OUR_REF>703868/589000</CP_OUR_REF>
  <CP_SYSTEM_DATE>04/SEP/2044</CP_SYSTEM_DATE>
  <CP_FULLNAME>Fred Bloggs</CP_FULLNAME>
  <CP_EXTERNAL_REF>PD/363</CP_EXTERNAL_REF>
  <CP_FIRST_LINE>FAKE ADDRESS, FAKE STREET, FAKE TOWN</CP_FIRST_LINE>
  <CP_STD_PARA2></CP_STD_PARA2>
  <CP_STD_PARA_NWL_U>Fred Bloggs of Northumbrian Water.</CP_STD_PARA_NWL_U>
  <CP_STD_PARA_TP_U>
 of .</CP_STD_PARA_TP_U>
  <CP_STD_PARA_DATES>
This was requested on 02/AUG/2044 and completed on 03/AUG/2044.</CP_STD_PARA_DATES>
  <CP_ADDRESS_CR>FAKE ADDRESS
FAKE TOWN
NE00 0XU
</CP_ADDRESS_CR>
</DWHD_2013XML>
`;